#!/usr/bin/env python3

import statistics
import sys

def grouped(iterator, n):
    args=[iterator] * n
    return zip(*args)

with open(sys.argv[1], "r") as infile, open(sys.argv[1] + ".avgs", "w") as outfile:
    for group in grouped(infile, 5):
        outfile.write(str(statistics.mean([float(x) for x in group])) + "\n")
